# Cloudflare Pages Wrangler Configuration
name = "kvideo"
# 保持兼容日期，或者根据建议改为 2024-11-01
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 【关键点】必须添加这一行，否则 Cloudflare 会跳过此文件
pages_build_output_dir = ".vercel/output/static"

[vars]
# 环境变量建议在 Cloudflare 控制台加密设置
